name: print-to
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          build-root-directory: app
      - run: make install
      - run: make say-hello
